spring:
  cloud:
    config:
      enabled: false
    discovery:
      enabled: false
  datasource:
    url: jdbc:h2:mem:paymentdb-test;DB_CLOSE_DELAY=-1
  jpa:
    hibernate:
      ddl-auto: create-drop

eureka:
  client:
    enabled: false

payment:
  rejection-threshold: 100.00
