server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**
        - id: class-service
          uri: lb://class-service
          predicates:
            - Path=/api/classes/**
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/api/bookings/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
